### ISSUE TITLE
Issue using boot2docker 

### ISSUE THREAD

**Issue by tomav** [docker-library/rails#22]
Hi, i'm trying to use rails image with boot2docker on OSX, and I have the following error trying to create a rails app:

	# docker run -it --rm --user "$(id -u):$(id -g)" -v "$(pwd)":/usr/src/app -w /usr/src/app rails rails new my_app
	      create
	/usr/local/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /usr/src/app/my_app (Errno::EACCES)
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:210:in `each'
		from /usr/local/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:50:in `block in invoke!'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:49:in `invoke!'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:14:in `empty_directory'
		from /usr/local/bundle/gems/railties-4.2.0/lib/rails/generators/app_base.rb:138:in `create_root'
		from (eval):1:in `create_root'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
		from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
		from /usr/local/bundle/gems/railties-4.2.0/lib/rails/commands/application.rb:17:in `<top (required)>'
		from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /usr/local/bundle/gems/railties-4.2.0/lib/rails/cli.rb:14:in `<top (required)>'
		from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /usr/local/bundle/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
		from /usr/local/bundle/bin/rails:23:in `load'
		from /usr/local/bundle/bin/rails:23:in `<main>'

I tried passing real IDs for user and group instead of commands and had the same issue.
Any idea?

**Comment by tomav** [comment]
Fixed removing `--user "$(id -u):$(id -g)"`.
