### ISSUE TITLE
Undefined method for an in-built Ruby method - only occuring in Docker images

### ISSUE THREAD

**Issue by vmatekole** [docker-library/rails#27]
I have the following Image:
FROM rails:4.2.0
\# Copy Rails  app
COPY .  /apps
WORKDIR /apps
RUN bundle install
VOLUME ["/var/log/spree-vend"]
EXPOSE 3000

And have the following undefined method error for the built-in PP method, occurring only, within the Docker image called within a controller..

Processing by VendInventoryController#update as 
Apr 10 16:27:25 stg.okla.co.uk production.log: I, [2015-04-10T14:27:25.717912 #1]  INFO -- :   Parameters: {"domain_prefix"=>"oklahoma", "type"=>"inventory.update", "payload"=>"{\"id\":\"8dac979f-2a43-fda1-fd29-d566c586ce60\",\"product_id\":\"b8ca3a6e-7230-11e4-efc6-a7a97d2062f7\",\"outlet_id\":\"bc305bf5-da30-11e4-f357-ddfb498dd76e\",\"attributed_cost\":\"1.25\",\"count\":\"40\",\"reorder_point\":\"3\",\"restock_level\":\"12\",\"product\":{\"id\":\"b8ca3a6e-7230-11e4-efc6-a7a97d2062f7\",\"sku\":\"13211\",\"handle\":\"KatieLeamoncardcongratswreath\",\"source\":\"USER\",\"active\":\"1\",\"name\":\"Katie Leamon card congrats wreath\",\"base_name\":\"Katie Leamon card congrats wreath\",\"description\":\"\",\"supply_price\":\"1.25\",\"taxes\":[{\"outlet_id\":\"bc305bf5-da30-11e4-f357-ddfb498dd76e\",\"tax_id\":\"9ad7f284-d87d-11e2-a415-bc764e10976c\"},{\"outlet_id\":\"ea7bc68f-b40e-11e3-a0f5-b8ca3a64f8f4\",\"tax_id\":\"9ad7f284-d87d-11e2-a415-bc764e10976c\"},{\"outlet_id\":\"bc305bf5-da30-11e4-f357-ddfb498dd76e\",\"tax_id\":\"9ad7f284-d87d-11e2-a415-bc764e10976c\"}]},\"outlet\":{\"id\":\"9adf8a87-d87d-11e2-a415-bc764e10976c\",\"name\":\"Oklahoma Gift\",\"time_zone\":\"Europe\\/London\",\"tax_id\":\"9ad7f284-d87d-11e2-a415-bc764e10976c\"}}", "version"=>"1"}
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.722798 #1] ERROR -- : Exception occured: NoMethodError - undefined method `pp' for #<VendInventoryController:0x007fbfccc8b688>
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.722880 #1] ERROR -- : Exception backtrace:
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723016 #1] ERROR -- : => /apps/app/controllers/base_controller.rb:16:in `parse_request'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723096 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723175 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723268 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723353 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723423 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723508 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723579 #1] ERROR -- : => /usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723648 #1] ERROR -- : => /usr/local/bundle/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
Apr 10 16:27:25 stg.okla.co.uk production.log: E, [2015-04-10T14:27:25.723746 #1] ERROR -- : => /usr/local/bundle/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
Apr 10 16:27:25 stg.okla.co.uk production.log: D, [2015-04-10T14:27:25.726717 #1] DEBUG -- : Exception raised: NoMethodError: undefined method `pp' for #<VendInventoryController:0x007fbfccc8b688>

**Comment by vmatekole** [comment]
Turns out that a require is needed. Not sure why locally it is not required and with in Docker image it is. Then again I am a newbie to Ruby.
